#!/bin/sh

GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Get vendor name by ID
get_vendor_name() {
    case $1 in
        0x1002) echo "AMD";;
        0x1010) echo "ImgTec";;
        0x10de) echo "NVIDIA";;
        0x13b5) echo "ARM";;
        0x5143) echo "Qualcomm";;
        0x8086) echo "INTEL";;
        *) echo "Unknown ($1)";;
    esac
}

# Function to format uptime
format_uptime() {
    local uptime_seconds=$(awk '{print int($1)}' /proc/uptime)
    local minutes=$((uptime_seconds / 60))
    local hours=$((minutes / 60))
    local days=$((hours / 24))
    local months=$((days / 30))
    
    if [ "$months" -ge 1 ]; then
        echo "${months} months"
    elif [ "$days" -ge 1 ]; then
        echo "${days} days"
    elif [ "$hours" -ge 1 ]; then
        echo "${hours} hours"
    else
        echo "${minutes} minutes"
    fi
}

# Get OS pretty name
os_name=$(awk -F= '/^PRETTY_NAME/ {print $2}' /etc/os-release | tr -d '"' 2>/dev/null || uname -o)

# Get kernel version
kernel_version=$(uname -r)

# Display OS and kernel info
echo -e "${GREEN}OS${NC}\t$os_name"
echo -e "${GREEN}Kernel${NC}\t$kernel_version"

# Display uptime if available
if [ -f /proc/uptime ]; then
    uptime=$(format_uptime)
    echo -e "${GREEN}Uptime${NC}\t$uptime"
fi

# Get and display CPU info
if [ -f /proc/cpuinfo ]; then
    cpu=$(awk -F ': ' '/^model name/ {print $2; exit}' /proc/cpuinfo)
    threads=$(awk '/^processor/ {count++} END {print count}' /proc/cpuinfo)
    echo -e "${GREEN}CPU${NC}\t$cpu ($threads threads)"
fi

# Get and display RAM info
if [ -f /proc/meminfo ]; then
    ram_info=$(free -m | awk '/^Mem:/ {used=$3; total=$2; print used, total}')
    used_ram=$(echo $ram_info | awk '{print $1}')
    total_ram=$(echo $ram_info | awk '{print $2}')
   echo -e "${GREEN}RAM${NC}\t${used_ram}MiB / ${total_ram}MiB"
fi

# Get and display GPU info
if [ -d /sys/class/drm ]; then
    for gpu in /sys/class/drm/card*; do
        if [ -d "$gpu/device" ]; then
            vendor=$(cat "$gpu/device/vendor")
            device=$(cat "$gpu/device/device")
            vendor_name=$(get_vendor_name $vendor)
            echo -e "${GREEN}GPU${NC}\t$vendor_name - $device"
        fi
    done
fi
